markers = {'Coelomic_Epithelium': ['UPK3B', 'LRRN4', 'KLK11'],
 'Master_TFs': ['GATA2', 'GATA4', 'LHX9', 'LHX1', 'EMX2', 'WT1', 'NR2F2', 'TBX4', 'TBX5', 'FOXF1', 'FOXF2', 'SIX1'],
 'MüllerianDuct_Epithelium': ['EPCAM','PAX8','PAX2','WNT7A','SOX17', 'FGF20', 'GDNF', 'CALCA','LYPD1', 'PNOC'], 
 'FallopianTube_Epithelium': ['TTYH1', 'LAMP5', 'PART1','ERP27','DAPL1','LYPD1', 'PNOC'],
 'UteroCervix_Epithelium': ['DLX5', 'UCA1', 'MSX1'],
 'MüllerianVagina_Epithelium': ['TP63', 'DLX5', 'UCA1', 'PAX2', 'PAX8'],
 'VaginalPlate_Epithelium' : ['GATA3', 'FOXA1', 'KRT5', 'HOXB13', 'PRAC1', 'SHH'],
 'WolffianDuct_Epithelium': ['GATA3','WNT9B','MMP7'],
 'Epididymis_Epithelium' : ['SPAG11B',], 
 'VasDeferens_Epithelium' : ['SPINK2'], 
 'Prostate_Epithelium' : ['HOXB13', 'PRAC1', 'SHH'],
 'UrogenitalSinus_Epithelium' : ['SHH', 'HOXB13', 'PRAC1'],
 'UrothelialUmbrellaCell' : ['SPINK1', 'SNX31'], 
 'GenitalEpidermis' : ['KRT14'], 
 'Mesenchymal': ['PDGFRA','DCN','COL1A1','HOXA7', 'HOXC4', 'HOXA9','HOXA10','HOXA11','HOXA13','HOXD13',
  'ISL1','WNT4','WNT5A'],
 'SmoothMuscle' : ['MYH11', 'ACTA2', 'DES', 'TAGLN'], 
 'Ligament' : ['C7', 'PTGER3', 'PRDM8'], 
 'Glans' : ['ISL1', 'DLX5', 'BAMBI'], 
 'CorpusCavernosum' : ['ISL1', 'SOX9', 'ZFHX4'], 
 'CorpusSpongiosum' : ['FOXF1', 'TCF21'], 
'Kidney_DistalTubule' : ['TMEM52B', 'DEFB1'], 
'Kidney_LoopOfHenle' : ['SLC12A1', 'ACPP'], 
 'Kidney_SShapedBody' : ['TM4SF4', 'PCP4'], 
 'Kidney_UretericBud' : ['AMN', 'FMO1'], 
 'Kidney_Podocyte' : ['NPHS1', 'NPHS2', 'PTPRO'], 
 'AdrenalCortex' : ['SHISA3', 'CDH9'],
  
 'Pre-PV': ['HEYL', 'MSC', 'ANGPT2', 'FOXS1'],
 'Perivascular': ['ACTA2', 'RGS5', 'STEAP4', 'RERGL', 'COX412', 'SEPTIN4'],
 'Immune': ['PTPRC', 'CD68', 'CD3E', 'MS4A1', 'JCHAIN'],
 'Endothelial': ['CDH5', 'LYVE1', 'PROX1', 'PLVAP'],
 'Neural': ['STMN2', 'GATA3', 'INA'],
 'SchwannCell' : ['MPZ', 'PLP1'],
 'Erythroid': ['HBA1', 'HBB', 'ALAS2'],
 'Hormone_receptors': ['AR','ESR1','ESR2','AMHR2','PGR','AVCR2','BMPR1A','SMAD1','SMAD5','SMAD8'],
 'Male_specific': ['SRY', 'RPS4Y1', 'DDX3Y'],
 'Gonads': ['DAZL','STRA8','FIGLA','MORC1','NR5A1','WNT6','AMH','SOX9','INSL3','STAR',
  'IRX3','OSR1','CALB2','LHX2','RDH10'] 
}
